# Generated by Django 3.2.12 on 2022-02-22 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmbulanceDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambulance_detection_video', models.FileField(blank=True, upload_to='ambulance_detection/video/')),
                ('ambulance_detection_audio', models.FileField(blank=True, upload_to='ambulance_detection/audio/')),
            ],
        ),
    ]
